# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Options JVM pour la mémoire du daemon Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Configuration Cache pour accélérer les builds
org.gradle.configuration-cache=true

# Style de code Kotlin
kotlin.code.style=official

# Activation d'AndroidX et Jetifier
android.useAndroidX=true
android.enableJetifier=true